### ISSUE TITLE
-nm NM, --number_molecules NM question

### ISSUE THREAD

**Issue by Tato14** [pinellolab/AmpUMI#1]
I would like to know how to calculate the number of molecules in a experiment. In targeted DNA seq, it has something to do with coverage? Million reads per sample? Amplicons per run?
Thanks

**Comment by Tato14** [comment]
Also, I would like to know if this calculation could be adapted to hybridization-capture based assays.

**Comment by kclem** [comment]
Hi @Tato14,

The number of molecules depends on the cells you are using. 

After DNA extraction, you can measure the weight of DNA, then divide it by the weight of a single genome to estimate the number of molecules in your reaction.

For example, the human diploid genome weighs around 3.59 x 10<sup>-12</sup> grams. So if you have 1ng (1x10<sup>-9</sup>) of DNA, this represents 278.6 diploid genomes, or ~557 molecules. If you amplify several amplicons from this material, each amplicon will still have 557 molecules. This is the parameter you will use for `-nm` for AmpUMI.

I don't quite understand your second question. The number of input molecules does not depend on coverage, reads or amplicons, so the calculation above should be able to be adapted to hybridization-capture based assays.

However, you may be asking if the number of UMIs for PCR amplification could be analogous to the number of hybridization probes? 

In the UMI question, if too few UMIs are added to the molecules, the same UMI may attach to different molecules, so AmpUMI deals with trying to find a large enough UMI pool so that you can be confident that your UMIs actually represent unique molecules. 

If in your hybridization question you are introducing multiple copies of UMI-tagged hybridization probes, where the same UMI can appear multiple times, yes, this is a similar question where you are trying to find a large-enough UMI-probe pool so that you can be confident that a UMI corresponds to only one probe-molecule pair.

However, if you are wondering how many un-tagged (no UMI) probes to introduce to saturate the number of molecules, this is a different question because you don't have to worry about the same probe hybridizing to two molecules. Instead, you can use the same number of hybridization probes as molecules and expect that your hybridization probes will saturate the number of molecules.
